# Generated by Django 5.0.6 on 2024-05-30 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_insight', '0002_budgetinsight_month'),
        ('system_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetinsight',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_management.profile'),
        ),
    ]
